services:
  root:
    build: .
    container_name: dns-root
    command: serverDNS 53 /uri
    volumes: [./uri/root:/uri:ro]
    networks:
      dnsnet:
        ipv4_address: 172.28.0.10

  tld:
    build: .
    container_name: dns-tld
    command: serverDNS 53 /uri
    volumes: [./uri/tld:/uri:ro]
    networks:
      dnsnet:
        ipv4_address: 172.28.0.11

  auth:
    build: .
    container_name: dns-auth
    command: serverDNS 53 /uri
    volumes: [./uri/auth:/uri:ro]
    networks:
      dnsnet:
        ipv4_address: 172.28.0.12

  resolver:
    build: .
    container_name: resolver
    command: resolver 53 172.28.0.10 53   
    depends_on:
      - root
      - tld
      - auth
    ports:
      - "5354:53/udp"
      - "5354:53/tcp"
    networks:
      dnsnet:
        ipv4_address: 172.28.0.20

  client:
    image: alpine
    container_name: dns-client
    command: sh -c "apk add --no-cache bind-tools && tail -f /dev/null"
    tty: true
    stdin_open: true 
    depends_on:
      - resolver
    networks:
      dnsnet:
        ipv4_address: 172.28.0.100

networks:
  dnsnet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
